### ISSUE TITLE
Grammar Issues on Front Page

### ISSUE THREAD

**Issue by modelmat** [Chameleon-Vision/chameleon-vision.github.io#1]
The front page contains text that is misleading and does not read well.
![image](https://user-images.githubusercontent.com/25718989/70127815-e0931b80-16cf-11ea-8259-76a0eeeba729.png)
Suggested alternatives (something nice preferably)
* Just install and all the target tracking is taken care of
* No need for any advanced vision knowledge

Similarly, under `Why Choose Chameleon Vision`.

The page also seems to suggest that no programming is needed - however, this is only technically true (given for actual processing the camera targets).

**Comment by oriagranat9** [comment]
changed the text
